[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitc-02
framework = espidf
upload_port = /dev/cu.usbmodem101
monitor_port = /dev/cu.usbmodem101
monitor_speed = 115200
board_build.flash_mode = dio
